controller:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  nodeSelecetor:
    ingress-ready: "true"
    kubernetes.io/os: linux
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
