apiVersion: v1
kind: Secret
metadata:
  name: shop-secrets
type: Opaque
stringData:
    APP_KEY: {{ .Values.secrets.appkey | quote }}
    DB_PASSWORD: {{ .Values.secrets.dbpassword | quote }}
    REDIS_PASSWORD: {{ .Values.secrets.redispass | quote }}
